### PR TITLE
Version sourcing

### LINKED ISSUE #95: Version sourcing
incorrect version

```
+ /home/omero/omeroenv/bin/pip install omego==0.4.0
You are using pip version 7.1.0, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting omego==0.4.0
  Downloading omego-0.4.0.tar.gz
  Requested omego==0.4.0 from https://pypi.python.org/packages/a8/11/323d146d44fb1cf85f561213ffe52bc90fd661c0ed072886c64ade4b000c/omego-0.4.0.tar.gz#md5=acebfa3b1588c90aae0c201eb0b02864, but installing version None
Collecting yaclifw>=0.1.1 (from omego==0.4.0)
  Downloading yaclifw-0.1.2.tar.gz
Collecting argparse (from yaclifw>=0.1.1->omego==0.4.0)
  Downloading argparse-1.4.0-py2.py3-none-any.whl
Building wheels for collected packages: omego, yaclifw
  Running setup.py bdist_wheel for omego
  Stored in directory: /home/omero/.cache/pip/wheels/ca/f3/1c/fe442d9e65866cd93074936cf2dd21a245ec27476082b9edb9
  Running setup.py bdist_wheel for yaclifw
  Stored in directory: /home/omero/.cache/pip/wheels/6f/68/84/fe07e9112771e8a3c2daf6540556e1df76e979b161a2b4e71b
Successfully built omego yaclifw
Installing collected packages: argparse, yaclifw, omego
Successfully installed argparse-1.4.0 omego-UNKNOWN yaclifw-0.1.2
```

### PR DESCRIPTION
**Pull request by sbesson**
Fixes #95 

## Current status

The current implementation of the package version sourcing in `omego` relies on the `yaclifw.get_git_version` API to retrieve the version from the current Git tag and create the `omego/RELEASE-VERSION` file.

As shown in #95, the main caveat is that in fresh environment, `yaclifw` is only collected in the dependencies step and the version is marked as `UNKNOWN` see `virtualenv /tmp/venv && /tmp/venv/bin/pip install omego==0.6.4`. This absence creates further deployment issues in the `openmicroscopy.omego` Ansible role - see https://github.com/openmicroscopy/ansible-role-omego/issues/2.

Additionally as discussed in https://github.com/ome/omego/issues/95#issuecomment-297030052, most of our Python packages are maintaing the source of the package version either in `setup.py` or in a dedicated resource file.

## Changes

This PR addresses the issue by moving the version text file under version control and consuming it directly both in `setup.py` and the code (see option 4 of https://packaging.python.org/guides/single-sourcing-package-version/#single-sourcing-the-version). For releases and development lifecycles, this means that bumping this version will become part of the release workflow (probably alongside the `CHANGELOG` pre-release PR).

Here the version text file is maintained as `omego/RELEASE-VERSION` as:
1- it is preserving the statu quo i.e. the current target location of `yaclifw.get_git_version()`
2- this file is included in `MANIFEST.in`
3- `<packagename>/RELEASE-VERSION` is part of the contract of the `yaclifw.Version` command. Keeping the name it allows to implement a compatible change without upstream modifications or overriding the API.

## Testing

In addition to checking that Travis and the tests remains green, the installation of the package should be carefully tested i.e.:

```
$ virtualenv /tmp/venv
$ source /tmp/venv/bin/activate
$ python setup.py install (from this repo) 
OR $ pip install git+git://github.com/sbesson/omego.git@version#egg=omego
$ omego version (should return a dev1 version)
$ pip freeze (should not contain `UNKNOWN`)
$ omego -h
$ omego download -h
```

### Caveats and limitations

As suggested in https://github.com/ome/omego/issues/95#issuecomment-310643214, a limitation of this patch is that while the `omego version` command should remain fully functional, the `yaclifw.Version` API contains some logic to overwrite the `RELEASE-VERSION` file under certain conditions - see https://github.com/openmicroscopy/yaclifw/blob/v0.1.1/yaclifw/version.py#L126.
However, additional testing shows that this situation would only happen in edge cases, primarily within a Git repository, and I have not been able to hit this codepath in a package installed either via `pip install git+git://` or `python setup.py install` so I would expect this limitation to have no impact  on real deployments.

### CODE REVIEW

**Comment by manics** [comment]
Looks fine to me. Since `RELEASE-VERSION` seems to be the only non-code file could it be [read with `pkg_resources`](http://setuptools.readthedocs.io/en/latest/setuptools.html#accessing-data-files-at-runtime) and the [`ZIP_SAFE = False` flag removed](http://setuptools.readthedocs.io/en/latest/setuptools.html#setting-the-zip-safe-flag)?

**Comment by joshmoore** [comment]
Definitely in favor of being `ZIP_SAFE` if possible.

**Comment by sbesson** [comment]
After reading more about the above, pushed an extra commit which overrides the base `yacfliw.Version` command to use the `pkg_resources` ResourceManager and set `ZIP_SAFE=True`. In my local testing, `python setup.py install` now installs a egg and `/tmp/venv/bin/omego version` returns the expected value. Relisting for a second round of review.

**Comment by manics** [comment]
Looks good to me
```
$ ./setup.py bdist_egg
$ easy_install dist/omego-0.6.5.dev1-py2.7.egg
$ omego version
0.6.5.dev1
```

**Comment by sbesson** [comment]
I'll need another PR for the version bump and version history before releasing and the latter can probably happen on Monday.

**Comment by joshmoore** [comment]
Understood :+1:

**Pull request merged**
