### PR TITLE
Remove old files

### PR DESCRIPTION
**Pull request by joshmoore**
As mentioned by @mancs during the devx chat, there are still a number of files in the omego source directory that could be moved elsewhere. I had begun doing this but never completed the migration. Primary question is if @pwalczysko is still using them at all. Eventually the plan is to have all of this functionality covered by the CLI importer. /cc @ximenesuk

### CODE REVIEW

**Comment by manics** [comment]
Should we do something here?

**Comment by sbesson** [comment]
NO veto to merging this from me.

**Comment by pwalczysko** [comment]
No veto to merging here either.

**Comment by joshmoore** [comment]
Ok. I'll merge to tidy up and then we can see where we go from there.

**Pull request merged**
