### PR TITLE
db upgrade --dry-run sets exit code status

### LINKED ISSUE #100: db verify deployed schema
I think it is necessary to have a `verify` action. This would compare the currently deployed database schema version against the version omego is pointed at.

This would be useful for a non-CI docker environment. In this environment, an implicit upgrade is not desirable should there be a version mismatch. so something like

```bash
omego db verify --dbhost "$DBHOST" --dbuser "$DBUSER" --dbname "$DBNAME" \
                --dbpass "$DBPASS" --serverdir=OMERO.server && echo "Verified version"
```

The success could be used to continue without a) installing/upgrading anything. If the version was not verified then an error exit code would be returned and potentially the output can be used to determine what to do, i.e. There is no schema deployed -> `init`, otherwise: error or `upgrade` depending on the use case.

Potentially a command which checks if any schema is installed at all could be separate which could in some use cases avoid having to parse the output at all.

### PR DESCRIPTION
**Pull request by manics**
`omego db upgrade --dry-run` returns:
- `0` if the database is up to date
- `2` if an upgrade is required
- `3` if the database needs to be initialised (table `dbpatch` is missing)

Closes #100 

Testing:
1. Create an empty database
2. `omego db upgrade --dry-run --serverdir OMERO.server-5.3.1-ice36-b61 --dbuser omero --dbpass omero --dbhost localhost --dbname omero` should set exit code `3`
3. Initialise an old database (pre 5.3). The above command should set exit code `2`
4. Run the above command without `--dry-run`, the database should be upgraded
5. Run the command again with `--dry-run`, it should exit `0`

### CODE REVIEW

**Comment by manics** [comment]
@dpwrussell How does this look?

**Comment by joshmoore** [comment]
```
E               AttributeError: No artifacts found for ice version: ice35
```

**Comment by manics** [comment]
Due to the issue highlighted in #101

**Comment by joshmoore** [comment]
Re-opening to trigger travis.

**Comment by joshmoore** [comment]
:+1: for including in 0.6.0

**Pull request merged**
